### ISSUE TITLE
is possible to make this work in Delphi 10.4 ?

### ISSUE THREAD

**Issue by thetoolwiz** [Laurensvanrun/Delphi-Promises#13]
Sorry ... delete this

**Comment by Laurensvanrun** [comment]
There is a PR for Tokyo support by removing inline variables. After review i will merge that one.

**Comment by thetoolwiz** [comment]
Sorry, the problem was I'm working with TMS WEB Core and it's missing a few things. It's not in Delphi per se. D10.4.2 has no problem with inline vars, although WEB Core doesn't support them. I found out about this from TMS where they announced support for it in their FNC Cloud Pack, which supports WEB Core. I'm not sure how they got the WEB Core support to work, although they did say it's "beta" code, so it's a work-in-progress. They may be using a beta version of pas2js and some updated libraries that haven't been published yet. But thanks for the reply. Anyway, this library solves issues I've been trying to untangle for a few years now. It seems you have to either use a bunch of callbacks, tons of anonymous methods, or approach it from a mainly multi-threading viewpoint where everything else is subordinate to that. You've managed to integrate the two so it's far more elegant and understandable, requiring just enough of both aspects to make it work.

**Comment by Laurensvanrun** [comment]
Thanks for your positive words. The reasons you name (callback hell or completely seperated in a thread per complete request/response) are exactly the reasons why I really loves promises in TypeScript. When I then started working on new Delphi services I wanted to have the same possibilities (including testing) and therefore I created this library :-)
